name: GitHub Custom Actions Demo
run-name: ${{ github.actor }} is testing tag triggers
on:
    push:
        tags:
            - "v[0-9]+\\.[0-9]+\\.[0-9]+-DEV[0-9]{2}/[0-9]{2}/[0-9]{2}"

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
