name: GitHub Custom Actions Demo
run-name: ${{ github.actor }} is testing branch ${{  github.ref_name }}
on:
  push:
    tags:
      - "v[0-9]+.0.0-DEV[0-9][0-9]/[0-9][0-9]/[0-9][0-9]"
    #   - "v[0-9][0-9].0.0-DEV[0-9][0-9]/[0-9][0-9]/[0-9][0-9]"

jobs:
  build: #job1
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered"
    # strategy:
    #   matrix:
    #     node-version: [18.x, 20.x, 22.x]
    # steps:
    #   - uses: actions/checkout@v4
    #   - name: Use Node.js ${{ matrix.node-version }}
    #     uses: actions/setup-node@v4
    #     with:
    #       node-version: ${{ matrix.node-version }}
    #       cache: "npm"
    #   - run: npm ci
    #   - run: npm run build --if-present
    #   - run: npm test
